#!/bin/bash


if [[ $# -ne 1 ]]; then
	echo "please give a valid file generated by perf sched script"
	exit
fi

orig_file=$1
file="fixed.${orig_file}"
cp $orig_file $file


sed -i 's/prev_state=S/prev_state=R/' $file
sed -i 's/prev_state=D/prev_state=S/' $file
sed -i 's/prev_state=T/prev_state=D/' $file
sed -i 's/prev_state=t/prev_state=T/' $file
sed -i 's/prev_state=X/prev_state=t/' $file
sed -i 's/prev_state=Z/prev_state=X/' $file
sed -i 's/prev_state=P/prev_state=Z/' $file
sed -i 's/prev_state=I/prev_state=P/' $file
sed -i 's/prev_state=R+/prev_state=I/' $file

echo "please use: $file"

# /* Used in tsk->state: */
# #define TASK_RUNNING            0x0000
# #define TASK_INTERRUPTIBLE      0x0001
# #define TASK_UNINTERRUPTIBLE        0x0002
# #define __TASK_STOPPED          0x0004
# #define __TASK_TRACED           0x0008
# /* Used in tsk->exit_state: */
# #define EXIT_DEAD           0x0010
# #define EXIT_ZOMBIE         0x0020
# #define EXIT_TRACE          (EXIT_ZOMBIE | EXIT_DEAD)
# /* Used in tsk->state again: */
# #define TASK_PARKED         0x0040
# #define TASK_DEAD           0x0080
# 
# /* get_task_state(): */
# #define TASK_REPORT         (TASK_RUNNING | TASK_INTERRUPTIBLE | \
#                      TASK_UNINTERRUPTIBLE | __TASK_STOPPED | \
#                      __TASK_TRACED | EXIT_DEAD | EXIT_ZOMBIE | \
#                      TASK_PARKED)
# 
# #define TASK_REPORT_IDLE    (TASK_REPORT + 1)
# #define TASK_REPORT_MAX     (TASK_REPORT_IDLE << 1)
# 
#     TP_printk("prev_comm=%s prev_pid=%d prev_prio=%d prev_state=%s%s ==> next_comm=%s next_pid=%d next_prio=%d",
#         __entry->prev_comm, __entry->prev_pid, __entry->prev_prio,
# 
#         (__entry->prev_state & (TASK_REPORT_MAX - 1)) ?
#           __print_flags(__entry->prev_state & (TASK_REPORT_MAX - 1), "|",
#                 { TASK_INTERRUPTIBLE, "S" },
#                 { TASK_UNINTERRUPTIBLE, "D" },
#                 { __TASK_STOPPED, "T" },
#                 { __TASK_TRACED, "t" },
#                 { EXIT_DEAD, "X" },
#                 { EXIT_ZOMBIE, "Z" },
#                 { TASK_PARKED, "P" },
#                 { TASK_DEAD, "I" }) :
#           "R",
# 
#         __entry->prev_state & TASK_REPORT_MAX ? "+" : "",
#         __entry->next_comm, __entry->next_pid, __entry->next_prio)
# 
